version: '3.8'

services:
  # Backend API
  backend:
    build: .
    container_name: vtry_backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=4000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_here}
      - PAYOS_CLIENT_ID=${PAYOS_CLIENT_ID}
      - PAYOS_API_KEY=${PAYOS_API_KEY}
      - PAYOS_CHECKSUM_KEY=${PAYOS_CHECKSUM_KEY}
      - PAYOS_RETURN_URL=${PAYOS_RETURN_URL}
      - PAYOS_CANCEL_URL=${PAYOS_CANCEL_URL}
      - PAYOS_WEBHOOK_URL=${PAYOS_WEBHOOK_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
    volumes:
      - ./upload:/app/upload
      - ./logs:/app/logs
    networks:
      - vtry_backend_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  vtry_backend_network:
    driver: bridge 